-- 코드를 작성해주세요
SELECT COUNT(*) AS COUNT, GENERATION 
  FROM (
    SELECT e.ID,
    CASE 
        WHEN e.PARENT_ID IS NULL THEN 1
        WHEN p1.PARENT_ID IS NULL THEN 2
        WHEN p2.PARENT_ID IS NULL THEN 3
        WHEN p3.PARENT_ID IS NULL THEN 4
        WHEN p4.PARENT_ID IS NULL THEN 5
        WHEN p5.PARENT_ID IS NULL THEN 6
        WHEN p6.PARENT_ID IS NULL THEN 7
        WHEN p7.PARENT_ID IS NULL THEN 8
        WHEN p8.PARENT_ID IS NULL THEN 9
        WHEN p9.PARENT_ID IS NULL THEN 10
        WHEN p10.PARENT_ID IS NULL THEN 11
        WHEN p11.PARENT_ID IS NULL THEN 12
        WHEN p12.PARENT_ID IS NULL THEN 13
        WHEN p13.PARENT_ID IS NULL THEN 14
        WHEN p14.PARENT_ID IS NULL THEN 15
        ELSE 16
    END AS GENERATION
    FROM ECOLI_DATA e
    LEFT JOIN ECOLI_DATA p1 ON e.PARENT_ID = p1.ID
    LEFT JOIN ECOLI_DATA p2 ON p1.PARENT_ID = p2.ID
    LEFT JOIN ECOLI_DATA p3 ON p2.PARENT_ID = p3.ID
    LEFT JOIN ECOLI_DATA p4 ON p3.PARENT_ID = p4.ID
    LEFT JOIN ECOLI_DATA p5 ON p4.PARENT_ID = p5.ID
    LEFT JOIN ECOLI_DATA p6 ON p5.PARENT_ID = p6.ID
    LEFT JOIN ECOLI_DATA p7 ON p6.PARENT_ID = p7.ID
    LEFT JOIN ECOLI_DATA p8 ON p7.PARENT_ID = p8.ID
    LEFT JOIN ECOLI_DATA p9 ON p8.PARENT_ID = p9.ID
    LEFT JOIN ECOLI_DATA p10 ON p9.PARENT_ID = p10.ID
    LEFT JOIN ECOLI_DATA p11 ON p10.PARENT_ID = p11.ID
    LEFT JOIN ECOLI_DATA p12 ON p11.PARENT_ID = p12.ID
    LEFT JOIN ECOLI_DATA p13 ON p12.PARENT_ID = p13.ID
    LEFT JOIN ECOLI_DATA p14 ON p13.PARENT_ID = p14.ID
    WHERE NOT EXISTS (
        SELECT 1 FROM ECOLI_DATA child 
        WHERE child.PARENT_ID = e.ID
    )
) result
GROUP BY GENERATION
ORDER BY GENERATION;